### PR TITLE
Translate error messages, especially message regarding CORS issue

### PR DESCRIPTION
**Pull request by gbastien**
Hi @liias 

we finally had issues with CORS in Chrome for example so decided to translate the error message for the user.

As tested, "en" is the fall-back language so when plug-in used with another language it will work as well.

I added the messages to the "et" language but could not translate it...

Thank you!

Gauthier

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @liias 

just a soft reminder, no worry, we have a local patch but in case ;-)

Thank you very much!

Gauthier

**Comment by liias** [comment]
Hey. Thanks! I think you also wanted to translate the French messages?

I'm good to merge translated error messages, though one issue is these messages are not very user friendly -  user might not really know what to do with that message (and it might be harder to google for it, unless adding some error code (numeric or text)).

**Comment by gbastien** [comment]
Hi @liias 

translated error messages are the original messages ;-)  But indeed it would be useful to turn it to something more readable.

To me the most important message is errorImageFromOtherDomain, others should really never happen...

I updated french translations.

Thank you and sorry for delay,

Gauthier

**Comment by liias** [comment]
Thanks for contribution (y)

**Pull request merged**
